dist: bionic
sudo: required
language: generic
services:
  - docker

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - cd grpcServer
  - make build
  - make push
  - cd ../tcpServer
  - make build
  - make push
