apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: grpc-echo
  name: grpc-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-echo
  template:
    metadata:
      labels:
        app: grpc-echo
    spec:
      containers:
        - name: grpc-echo
          image: killercai/grpc-echo:0.1.0
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: grpc-echo
spec:
  selector:
    app:  grpc-echo
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: grpc-echo
spec:
  rules:
    - host: grpc.example.com
      http:
        paths:
          - backend:
              serviceName: grpc-echo
              servicePort: grpc
            path: /
  # !!! tls is must for grpc with ingress
  # ssl secret should be create first
  tls:
    - secretName: grpc.example.com
      hosts:
        - grpc.example.com